"""Trace the footballer fan art (finished PNGs in the owner's Drive) into SVGs and rebuild the fan-art wall in index.html.

Usage: python -I tools/build_fan_art.py "G:/My Drive/Notion/.football" index.html
The wall shows a fresh random selection on every page load (script in index.html); all SVGs are listed here.
"""
import os
import pathlib
import re
import sys
import tempfile

import vtracer
from PIL import Image, ImageChops

PICKS = {  # slug -> path inside .football (finished, un-watermarked drawings; one or a few per player for variety)
    "cr7-2024": "cr7/cr7_2024.png", "cr7-turin": "cr7/cr7_turin.png", "cr7-madrid": "cr7/cr7_madrid.png",
    "cr7-madeira": "cr7/cr7_madeira.png", "cr7-manchester": "cr7/cr7_manchester.png",
    "cr7-manchester-again": "cr7/cr7_manchester_again.png", "cr7-classic": "cr7/Cr7.png",
    "neymar-psg": "Neymar/Neymar_psg20.png", "neymar-santos": "Neymar/Neymar_santos.png",
    "neymar-barca-14": "Neymar/Neymar_barca14.png", "neymar-barca-15": "Neymar/Neymar_barca15.png",
    "neymar-barca-16": "Neymar/Neymar_barca16.png", "neymar-brazil-14": "Neymar/Neymar_brazil14.png",
    "neymar-brazil-16": "Neymar/Neymar_brazil16.png", "neymar": "Neymar/Neymar.png",
    "messi-world-cup": "Messi/Messi_Argentina_WC.png", "messi": "Messi/Messi.png",
    "bellingham": "Bellingham/Bellingham.png", "rashford": "Rashford/Rashford_white background.png",
    "pele": "Pelé/Pelé.png", "haaland": "Haaland/Haaland.png", "lewandowski": "Lewy/Lewy.png",
    "benzema": "Benzema/Benzema.png",
}


def crop(src, pad=24):
    im = Image.open(src).convert("RGBA")
    flat = Image.alpha_composite(Image.new("RGBA", im.size, "white"), im).convert("RGB")
    mask = ImageChops.difference(flat, Image.new("RGB", flat.size, "white")).convert("L").point(lambda v: 255 if v > 24 else 0)
    l, t, r, b = mask.getbbox()
    box = (max(l - pad, 0), max(t - pad, 0), min(r + pad, flat.width), min(b + pad, flat.height))
    return flat.crop(box)


def main(root, page_path):
    root, out = pathlib.Path(root), pathlib.Path(page_path).parent / "assets" / "fan"
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("*.svg"):
        old.unlink()
    items = []
    for slug, rel in PICKS.items():
        src = root / rel
        if not src.exists():
            print("missing", rel)
            continue
        im = crop(src)
        im.thumbnail((1400, 1400))  # tracing needs no more than this; keeps files small
        with tempfile.TemporaryDirectory() as tmp:
            png = os.path.join(tmp, "in.png")
            im.save(png)
            dst = out / f"{slug}.svg"
            vtracer.convert_image_to_svg_py(png, str(dst), colormode="color", color_precision=8, layer_difference=6,
                                            filter_speckle=4, mode="spline", path_precision=1)  # fine steps keep gradients (hair fades) smooth
        items.append((slug, im.size, dst.stat().st_size))
    for slug, size, kb in items:
        print(f"{slug:<22} {size[0]}x{size[1]}  {kb // 1024} KB")

    figs = "".join(
        f'<img src="assets/fan/{slug}.svg" width="{w}" height="{h}" loading="lazy" alt="Notion-style fan art of a footballer">'
        for slug, (w, h), _ in items)
    block = ('    <!-- fan:start (generated by tools/build_fan_art.py) -->\n'
             f'    <figure class="fan-wall"><div class="fan-grid">{figs}</div>\n'
             '      <figcaption>Fan art, drawn off the clock.</figcaption></figure>\n'
             '    <!-- fan:end -->\n')
    page = open(page_path, encoding="utf-8").read()
    if "<!-- fan:start" in page:
        page, n = re.subn(r"    <!-- fan:start.*?<!-- fan:end -->\n", lambda m: block, page, flags=re.S)
    else:  # first run: replace the old single-image figure
        page, n = re.subn(r'    <figure class="parallax-x">.*?</figure>\n', lambda m: block, page, flags=re.S)
    assert n == 1, "fan-art figure not found"
    open(page_path, "w", encoding="utf-8").write(page)
    print(f"{len(items)} SVGs, {sum(k for _, _, k in items) // 1024} KB total")


if __name__ == "__main__":
    main(*sys.argv[1:3])
